/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package src;
import javax.swing.*;
import java.awt.BorderLayout;
import java.util.List;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import com.toedter.calendar.JDateChooser;
import com.toedter.calendar.JTextFieldDateEditor;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Arrays;
import java.util.Date;
/**
 *
 * @author quanglv
 */
public class Main extends javax.swing.JFrame {
    private UserManager userManager;
    private String username;
    private RecordManager recordManager;
    private DefaultTableModel model;
    private JTable table_info;
    private int id_row;
    private JDateChooser datePicker;
    private LineChartDrawer draw;
    private LineChartDrawer lineChartDrawer ;
    
    /**
     * Creates new form Main
     */
    public Main(UserManager userManager, String username) {
        this.userManager = userManager;
        this.username = username;
        initComponents();
        setLocationRelativeTo(null);
        edit_bt.setEnabled(false);
        delete_bt.setEnabled(false);
        hello_label.setText("Welcome "+ username+". Have nice day!");
        recordManager = new RecordManager(username);
        initializeTable();
        initializeDatePicker();
        initializeComboBox();
        initializeTableSelectionListener();
        initializeDrawer();
    }

    private void initializeTable() {
        model = new DefaultTableModel();
        model.addColumn("Date");
        model.addColumn("Speed(km/h)");
        model.addColumn("Time(min)");
        model.addColumn("Distance(km)");
        table_info = new JTable(model);
        table_info.setDefaultEditor(Object.class, null);
        JScrollPane scrollPane = new JScrollPane(table_info);
        jPanel1.setLayout(new BorderLayout());
        jPanel1.add(scrollPane, BorderLayout.CENTER);
        loadRecordToTable();
    }

    private void initializeDatePicker() {
        datePicker = new JDateChooser();
        datePicker.setDate(java.sql.Date.valueOf(java.time.LocalDate.now()));
        datePicker.setDateFormatString("yyyy-MM-dd");
        ((JTextFieldDateEditor) datePicker.getDateEditor()).setEditable(false);
        cal_panel.setLayout(new BorderLayout());
        cal_panel.add(datePicker);
    }
    
    private void initializeDrawer(){
        lineChartDrawer = new LineChartDrawer(recordManager, "Speed", 30);
        draw_panel.add(lineChartDrawer, BorderLayout.CENTER);
    }

    private void initializeComboBox() {
        String[] choices = {"Speed", "Time", "Distance"};
        for (String choice : choices) {
            type_cb.addItem(choice);
        }
    }

    private void initializeTableSelectionListener() {
        table_info.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                selectRowTable(evt);
            }
        });
    }
    
    
    private static void setDateToChooser(JDateChooser dateChooser, String dateString) {
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            Date date = sdf.parse(dateString);
            dateChooser.setDate(date);
        } catch (ParseException e) {
            e.printStackTrace();
        }
    }

    private void loadRecordToTable() {
        model.setRowCount(0); // Xóa dữ liệu cũ
        List<Record> records = recordManager.getAllRecords();
        for (Record record : records) {
            Object[] rowData = {record.getDate(), record.getSpeed(), record.getTime(), record.getDistance()};
            model.addRow(rowData); // Thêm dòng mới vào bảng
        }
    }

    private void switchToLoginPanel() {
        Login loginFrame = new Login(userManager);
        loginFrame.setVisible(true); // Hiển thị giao diện đăng nhập mới
        dispose(); // Giải phóng frame hiện tại
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        main_frame = new javax.swing.JTabbedPane();
        input_pannel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        pannel_bt = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cal_panel = new java.awt.Panel();
        jLabel2 = new javax.swing.JLabel();
        speed_tf = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        time_tf = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        distance_tf = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        add_bt = new javax.swing.JButton();
        edit_bt = new javax.swing.JButton();
        delete_bt = new javax.swing.JButton();
        clear_bt = new javax.swing.JButton();
        monitor_panel = new javax.swing.JPanel();
        draw_panel = new javax.swing.JPanel();
        items_panel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        type_cb = new javax.swing.JComboBox<>();
        apply_bt = new javax.swing.JButton();
        logout_bt = new javax.swing.JButton();
        hello_label = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        main_frame.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                main_frameStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 493, Short.MAX_VALUE)
        );

        jLabel1.setText("Date");

        javax.swing.GroupLayout cal_panelLayout = new javax.swing.GroupLayout(cal_panel);
        cal_panel.setLayout(cal_panelLayout);
        cal_panelLayout.setHorizontalGroup(
            cal_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        cal_panelLayout.setVerticalGroup(
            cal_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 39, Short.MAX_VALUE)
        );

        jLabel2.setText("Speed");

        jLabel6.setText("km/h");

        jLabel3.setText("Time");

        jLabel7.setText("s");

        jLabel4.setText("Distance");

        jLabel8.setText("km");

        add_bt.setText("Add");
        add_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_btActionPerformed(evt);
            }
        });

        edit_bt.setText("Update");
        edit_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_btActionPerformed(evt);
            }
        });

        delete_bt.setText("Delete");
        delete_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_btActionPerformed(evt);
            }
        });

        clear_bt.setText("Clear");
        clear_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_btActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pannel_btLayout = new javax.swing.GroupLayout(pannel_bt);
        pannel_bt.setLayout(pannel_btLayout);
        pannel_btLayout.setHorizontalGroup(
            pannel_btLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pannel_btLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(pannel_btLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pannel_btLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pannel_btLayout.createSequentialGroup()
                        .addComponent(distance_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pannel_btLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pannel_btLayout.createSequentialGroup()
                            .addComponent(speed_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(pannel_btLayout.createSequentialGroup()
                            .addComponent(time_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(cal_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pannel_btLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pannel_btLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(clear_bt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(delete_bt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(edit_bt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(add_bt, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72))
        );
        pannel_btLayout.setVerticalGroup(
            pannel_btLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pannel_btLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pannel_btLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(cal_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(pannel_btLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(speed_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pannel_btLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(time_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pannel_btLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(distance_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(add_bt)
                .addGap(18, 18, 18)
                .addComponent(edit_bt)
                .addGap(18, 18, 18)
                .addComponent(delete_bt)
                .addGap(18, 18, 18)
                .addComponent(clear_bt)
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout input_pannelLayout = new javax.swing.GroupLayout(input_pannel);
        input_pannel.setLayout(input_pannelLayout);
        input_pannelLayout.setHorizontalGroup(
            input_pannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(input_pannelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(pannel_bt, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        input_pannelLayout.setVerticalGroup(
            input_pannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(input_pannelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(input_pannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pannel_bt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        main_frame.addTab("Input", input_pannel);

        javax.swing.GroupLayout draw_panelLayout = new javax.swing.GroupLayout(draw_panel);
        draw_panel.setLayout(draw_panelLayout);
        draw_panelLayout.setHorizontalGroup(
            draw_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 968, Short.MAX_VALUE)
        );
        draw_panelLayout.setVerticalGroup(
            draw_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 445, Short.MAX_VALUE)
        );

        jLabel5.setText("Monitor data");

        apply_bt.setText("Apply");
        apply_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apply_btActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout items_panelLayout = new javax.swing.GroupLayout(items_panel);
        items_panel.setLayout(items_panelLayout);
        items_panelLayout.setHorizontalGroup(
            items_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(items_panelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(type_cb, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(apply_bt, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        items_panelLayout.setVerticalGroup(
            items_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(items_panelLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(items_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(type_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(apply_bt))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout monitor_panelLayout = new javax.swing.GroupLayout(monitor_panel);
        monitor_panel.setLayout(monitor_panelLayout);
        monitor_panelLayout.setHorizontalGroup(
            monitor_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(monitor_panelLayout.createSequentialGroup()
                .addGroup(monitor_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(draw_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(monitor_panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(items_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        monitor_panelLayout.setVerticalGroup(
            monitor_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(monitor_panelLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(items_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(draw_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        main_frame.addTab("Monitor", monitor_panel);

        logout_bt.setText("Logout");
        logout_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_btActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(hello_label, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(logout_bt, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(main_frame))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logout_bt)
                    .addComponent(hello_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(main_frame, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logout_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_btActionPerformed
        // TODO add your handling code here:
        switchToLoginPanel();
    }//GEN-LAST:event_logout_btActionPerformed
    
    private void selectRowTable(javax.swing.event.ListSelectionEvent e) {
        if (!e.getValueIsAdjusting()) {
            int selectedRow = table_info.getSelectedRow();
            if (selectedRow != -1) {
                enableEditDeleteButtons();
                id_row = selectedRow;
                // Lấy thông tin từ hàng được chọn
                Object date = table_info.getValueAt(selectedRow, 0);
                Object speed = table_info.getValueAt(selectedRow, 1);
                Object time = table_info.getValueAt(selectedRow, 2);
                Object distance = table_info.getValueAt(selectedRow, 3);
                // Hiển thị thông tin lên các trường nhập liệu
                setDateToChooser(datePicker, date.toString());
                speed_tf.setText(speed.toString());
                time_tf.setText(time.toString());
                distance_tf.setText(distance.toString());
            }
        }
    }

    private void enableEditDeleteButtons() {
        edit_bt.setEnabled(true);
        delete_bt.setEnabled(true);
        add_bt.setEnabled(false);
    }
    
    private void clearAndRedrawChart(String typeRecord) {
        // Xóa biểu đồ hiện tại nếu có
        if (draw != null) {
            draw_panel.removeAll();
            draw_panel.revalidate();
            draw_panel.repaint();
        }

        // Vẽ biểu đồ mới
        draw = new LineChartDrawer(recordManager, typeRecord, 30);
        draw_panel.setLayout(new BorderLayout());
        draw_panel.add(draw, BorderLayout.CENTER);

        // Hiển thị các thành phần trên panel
        monitor_panel.add(items_panel);
        monitor_panel.add(draw_panel);
    }

    
    private void main_frameStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_main_frameStateChanged
        // TODO add your handling code here:
        if (main_frame.getSelectedIndex() == 0) {//Input
            System.err.println("Hello");
        } else if (main_frame.getSelectedIndex() == 1) {//Monitor
            System.err.println("Bye");
            clearAndRedrawChart((String) type_cb.getSelectedItem());
        }
    }//GEN-LAST:event_main_frameStateChanged

    private void clearTextField(){
        datePicker.setDate(java.sql.Date.valueOf(java.time.LocalDate.now()));
        speed_tf.setText("");
        time_tf.setText("");
        distance_tf.setText("");
    }
    
    private void apply_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apply_btActionPerformed
        // TODO add your handling code here:
       clearAndRedrawChart((String) type_cb.getSelectedItem());
    }//GEN-LAST:event_apply_btActionPerformed

    private void clear_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_btActionPerformed
        // TODO add your handling code here:
        clearTextField();
    }//GEN-LAST:event_clear_btActionPerformed

    private void delete_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_btActionPerformed
        // TODO add your handling code here:
        loadRecordToTable();
        recordManager.deleteRecord(id_row);
        loadRecordToTable();
        add_bt.setEnabled(true);
        JOptionPane.showMessageDialog(Main.this, "Data deleted.");
    }//GEN-LAST:event_delete_btActionPerformed

    private void edit_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_btActionPerformed
        // TODO add your handling code here:
        // Lấy thông tin từ các trường nhập liệu
        java.util.Date selectedDate = datePicker.getDate();
        String speed =  speed_tf.getText();
        String time = time_tf.getText();
        String distance = distance_tf.getText();

        // Kiểm tra xem có trường nào rỗng không
        if (selectedDate == null || speed.isEmpty() || time.isEmpty() || distance.isEmpty()) {
            JOptionPane.showMessageDialog(Main.this, "The data field cannot be left blank.");
            return;
        }

        // Format ngày theo định dạng "yyyy-MM-dd"
        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd");
        String date = sdf.format(selectedDate);
        
        if (checkFloatType()){
            recordManager.updateRecord(id_row, date, Float.parseFloat(speed), Float.parseFloat(time), Float.parseFloat(distance));
            // Xóa các trường nhập liệu và load lại bảng
            clearTextField();
            loadRecordToTable();
            add_bt.setEnabled(true);
            JOptionPane.showMessageDialog(Main.this, "Update completed.");
        }else{
            JOptionPane.showMessageDialog(Main.this, "Incorrect data type, re-enter");
        }
        // Cập nhật dữ liệu
        
    }//GEN-LAST:event_edit_btActionPerformed
    
    private boolean checkFloatType(){
        try{
            Float.parseFloat(speed_tf.getText());
            Float.parseFloat(time_tf.getText());
            Float.parseFloat(distance_tf.getText());
            return true;
        }catch (Exception e){
            return false;
        }
    }
    
    private void add_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_btActionPerformed
        // Lấy ngày được chọn từ JDateChooser và định dạng thành chuỗi "yyyy-MM-dd"
        java.util.Date selectedDate = datePicker.getDate();
        String date = (selectedDate != null) ? new java.text.SimpleDateFormat("yyyy-MM-dd").format(selectedDate) : "";

        // Lấy dữ liệu từ các trường nhập liệu
        String speed = speed_tf.getText();
        String time = time_tf.getText();
        String distance = distance_tf.getText();
        
        // Kiểm tra xem các trường nhập liệu có rỗng không
        if (date.isEmpty() || speed.isEmpty() || time.isEmpty() || distance.isEmpty()) {
            JOptionPane.showMessageDialog(Main.this, "The data field cannot be left blank.");
            return;
        }
        if (checkFloatType()){
            // Thêm bản ghi mới vào cơ sở dữ liệu
            recordManager.addRecord(date, Float.parseFloat(speed), Float.parseFloat(time), Float.parseFloat(distance));
            // Xóa các trường nhập liệu và load lại bảng
            clearTextField();
            loadRecordToTable();
            JOptionPane.showMessageDialog(Main.this, "Add data completed.");
        }else{
            JOptionPane.showMessageDialog(Main.this, "Incorrect data type, re-enter");
        }
    }//GEN-LAST:event_add_btActionPerformed
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        String userDataFile = "/home/quanglv/NetBeansProjects/java_tutorial/src/main/java/com/quanglv/java_tutorial/users.csv";
        String recordsDirectory = "/home/quanglv/NetBeansProjects/java_tutorial/src/main/java/com/quanglv/java_tutorial/records";
        UserManager userManager = new UserManager(userDataFile, recordsDirectory);
        String username = "admin2";
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main(userManager, username).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_bt;
    private javax.swing.JButton apply_bt;
    private java.awt.Panel cal_panel;
    private javax.swing.JButton clear_bt;
    private javax.swing.JButton delete_bt;
    private javax.swing.JTextField distance_tf;
    private javax.swing.JPanel draw_panel;
    private javax.swing.JButton edit_bt;
    private javax.swing.JLabel hello_label;
    private javax.swing.JPanel input_pannel;
    private javax.swing.JPanel items_panel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton logout_bt;
    private javax.swing.JTabbedPane main_frame;
    private javax.swing.JPanel monitor_panel;
    private javax.swing.JPanel pannel_bt;
    private javax.swing.JTextField speed_tf;
    private javax.swing.JTextField time_tf;
    private javax.swing.JComboBox<String> type_cb;
    // End of variables declaration//GEN-END:variables
}
